### ISSUE TITLE
Resolve Actuator tests for Inventory, Customer, Auth

### ISSUE THREAD

**Issue by oiricaud** [ibm-garage-ref-storefront/planning#40]
Recall an actuator is mainly used to expose operational information about the running application – health, metrics, info, dump, env, etc. The actuator tests come when you run `appsody init ...`.

When running a kabanero pipeline the `Actuator` tests failed because the `appsody test` command is ran instead of `appsody test --docker-options "-e YOUR_ENV_VAR=your_env_value"`. We can resolve these issues on the microservices by introducing your properties using the @SpringBootTest annotation such as: 

```java
@RunWith(SpringRunner.class)
@SpringBootTest(properties = {"MYSQL_HOST=host.docker.internal", "MYSQL_PORT=3306", "MYSQL_DATABASE=inventorydb", "MYSQL_USER=dbuser", "MYSQL_PASSWORD=password", webEnvironment = WebEnvironment.RANDOM_PORT})
public class ActuatorTest {
```

Resolve ActuatorTests that failed are the following:
 
- [x] [Inventory](https://github.com/ibm-garage-ref-storefront/inventory-ms-spring)
- [x] [Customer](https://github.com/ibm-garage-ref-storefront/customer-ms-spring)
- [x] [Auth](https://github.com/ibm-garage-ref-storefront/auth-ms-spring)

**Comment by oiricaud** [comment]
Pull Requests:

Resolve ActuatorTests for the following microservices:
 
- [x] [pull-request-inventory](https://github.com/ibm-garage-ref-storefront/inventory-ms-spring/pull/11)
- [x] [pull-request-auth](https://github.com/ibm-garage-ref-storefront/auth-ms-spring/pull/4)
- [x] [pull-request-customer](https://github.com/ibm-garage-ref-storefront/customer-ms-spring/pull/15)
**Note**
The other microservices Actuator tests did not fail, but this assumes that the user has their databases preconfigured

**Comment by phemankita** [comment]
@oiricaud I tested inventory ... So to run `appsody test` do we still need the mysql server to be up and running ?

```[Container] The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[Container] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Container] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Container] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Container] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[Container] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[Container] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[Container] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[Container] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[Container] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
[Container] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[Container] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
[Container] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
[Container] 	... 81 more
[Container] Caused by: java.net.ConnectException: Connection refused (Connection refused)
[Container] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[Container] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[Container] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[Container] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[Container] 	at java.net.Socket.connect(Socket.java:607)
[Container] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[Container] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
[Container] 	... 84 more
[Container] 
[Container] 
[Container] Results :
[Container] 
[Container] Tests in error: 
[Container]   testHealthEndpoint(application.inventory.ActuatorTest): Failed to load ApplicationContext
[Container]   testLivenessEndpoint(application.inventory.ActuatorTest): Failed to load ApplicationContext
[Container]   contextLoads(application.inventory.ActuatorTest): Failed to load ApplicationContext
[Container]   testPrometheusEndpoint(application.inventory.ActuatorTest): Failed to load ApplicationContext
[Container]   testMetricsEndpoint(application.inventory.ActuatorTest): Failed to load ApplicationContext
[Container] 
[Container] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
[Container] 
[Container] [INFO] ------------------------------------------------------------------------
[Container] [INFO] BUILD FAILURE
[Container] [INFO] ------------------------------------------------------------------------
[Container] [INFO] Total time:  01:18 min
[Container] [INFO] Finished at: 2020-06-26T10:19:42Z
[Container] [INFO] ------------------------------------------------------------------------
[Container] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project inventory-application: There are test failures.
[Container] [ERROR] 
[Container] [ERROR] Please refer to /project/user-app/target/surefire-reports for the individual test results.
[Container] [ERROR] -> [Help 1]
[Container] [ERROR] 
[Container] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[Container] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[Container] [ERROR] 
[Container] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[Container] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Container] [Error] Wait received error with status code: 1 due to error: exit status 1
[Error] Error in 'appsody test': exit status 1
