### ISSUE TITLE
Appsodify catalog microservice

### ISSUE THREAD

**Issue by phemankita** [ibm-garage-ref-storefront/planning#48]
- Use Appsody `java-openliberty` stack
- Update the Catalog app to use the microprofile version that matches the current appsody stack. 

Repo - https://github.com/ibm-garage-ref-storefront/catalog-ms-openliberty

Old Repo - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-catalog/tree/microprofile

Note: Make sure the api rest endpoints are same as the ones we using the spring version so that the web app will be functional for both of them. If they are different in th eolder version, change them to match the current spring version.

Endpoint - `/micro/items`

**Comment by phemankita** [comment]
The rest client is not able to hit the url and retrieve info

```[Container] [INFO] [WARNING ] Interceptor for {http://client.application.appsody.dev/}InventoryServiceClient has thrown exception, unwinding now
[Container] [INFO] java.lang.NullPointerException
[Container] [INFO] [err] javax.ws.rs.ProcessingException: java.lang.NullPointerException
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:640)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:616)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:897)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:343)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.invokeActual(MicroProfileClientProxyImpl.java:438)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.access$000(MicroProfileClientProxyImpl.java:73)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl$Invoker.call(MicroProfileClientProxyImpl.java:460)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.cdi.CDIInterceptorWrapperImpl.invoke(CDIInterceptorWrapperImpl.java:190)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.invoke(MicroProfileClientProxyImpl.java:433)
[Container] [INFO] [err] 	at com.sun.proxy.$Proxy91.getAllItems(Unknown Source)
[Container] [INFO] [err] 	at dev.appsody.application.rest.InventoryRefreshTask.run(InventoryRefreshTask.java:30)
[Container] [INFO] [err] Caused by: 
[Container] [INFO] [err] java.lang.NullPointerException
[Container] [INFO] [err] 	at com.ibm.ws.opentracing.OpentracingUtils.lookupAppName(OpentracingUtils.java:82)
[Container] [INFO] [err] 	at com.ibm.ws.opentracing.OpentracingTracerManager.getTracer(OpentracingTracerManager.java:141)
[Container] [INFO] [err] 	at com.ibm.ws.opentracing.OpentracingClientFilter.filter(OpentracingClientFilter.java:92)
[Container] [INFO] [err] 	at com.ibm.ws.microprofile.opentracing.rest.client.listener.OpentracingRestClientFilter.filter(OpentracingRestClientFilter.java:59)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.spec.ClientRequestFilterInterceptor.handleMessage(ClientRequestFilterInterceptor.java:73)
[Container] [INFO] [err] 	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:712)
[Container] [INFO] [err] 	at org.apache.cxf.microprofile.client.proxy.MicroProfileClientProxyImpl.doRunInterceptorChain(MicroProfileClientProxyImpl.java:175)
[Container] [INFO] [err] 	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:895)
[Container] [INFO] [err] 	... 8 more```

**Comment by phemankita** [comment]
We have this issue https://github.com/OpenLiberty/open-liberty/issues/11582 here. There was a problem like this before and the fix is released for the `openliberty version 20.0.0.5` but the current stack is using `openliberty version 20.0.0.3`

I checked with one of the devs working on stacks and they have a PR ready for updated version pointing to `20.0.0.6` and mentioned that they will be updating it in next couple of days. They suggested us to re-build if needed.

@csantanapr do we want to wait on them for the fix or go ahead and build a local stack to make things work ?

**Comment by csantanapr** [comment]
Let's build our own and push it to DockerHub for now

**Comment by csantanapr** [comment]
Past experience they take for ever to pick updates on stacks.

**Comment by phemankita** [comment]
https://github.com/ibm-garage-ref-storefront/catalog-ms-openliberty/pull/1
